DROP SEQUENCE IF EXISTS HIBERNATE_SEQUENCE;
CREATE SEQUENCE HIBERNATE_SEQUENCE MINVALUE 0 MAXVALUE 99999999999999 INCREMENT BY 1 START WITH 100 CACHE 20;

DROP SEQUENCE IF EXISTS APP_SEQ;
CREATE SEQUENCE APP_SEQ MINVALUE 0 MAXVALUE 99999999999999 INCREMENT BY 1 START WITH 100 CACHE 20;

DROP TABLE IF EXISTS APP_AUDIT;
CREATE TABLE APP_AUDIT (
  VERSION_NUMBER NUMERIC NOT NULL PRIMARY KEY,
  EVENT_TYPE     NUMERIC NOT NULL,
  VERSION_TIME   NUMERIC NOT NULL,
  USER_ID        NUMERIC NOT NULL
);

DROP TABLE IF EXISTS ROLE;
CREATE TABLE ROLE
(
  ID          NUMERIC      NOT NULL PRIMARY KEY,
  ACTIVE_FLAG BOOLEAN      NOT NULL,
  NAME        VARCHAR(200) NOT NULL UNIQUE,
  DESCRIPTION VARCHAR(1000)
);

DROP TABLE IF EXISTS ROLE_AUD;
CREATE TABLE ROLE_AUD
(
  ID               NUMERIC      NOT NULL,
  ACTIVE_FLAG      BOOLEAN      NOT NULL,
  NAME             VARCHAR(200) NOT NULL UNIQUE,
  DESCRIPTION      VARCHAR(1000),
  VERSION_NUMBER   NUMERIC      NOT NULL,
  TRANSACTION_TYPE NUMERIC      NOT NULL,
  CONSTRAINT ROLE_AUD_PK PRIMARY KEY (ID, VERSION_NUMBER)
);

DROP TABLE IF EXISTS APP_USER;
CREATE TABLE APP_USER
(
  ID          NUMERIC      NOT NULL PRIMARY KEY,
  FIRST_NAME  VARCHAR(250) NOT NULL,
  LAST_NAME   VARCHAR(250) NOT NULL,
  PASSWORD    VARCHAR(200) NOT NULL,
  USER_NAME    VARCHAR(200),
  EMAIL       VARCHAR(200) NOT NULL,
  MOBILE      VARCHAR(12)      NOT NULL,
  ACTIVE_FLAG BOOLEAN      NOT NULL
);

DROP TABLE IF EXISTS APP_USER_AUD;
CREATE TABLE APP_USER_AUD
(
  ID               NUMERIC      NOT NULL,
  FIRST_NAME       VARCHAR(250) NOT NULL,
  LAST_NAME        VARCHAR(250) NOT NULL,
  USER_NAME         VARCHAR(200),
  PASSWORD         VARCHAR(200) NOT NULL,
  EMAIL            VARCHAR(200) NOT NULL,
  MOBILE           VARCHAR(12) NOT NULL,
  ACTIVE_FLAG      BOOLEAN      NOT NULL,
  VERSION_NUMBER   NUMERIC      NOT NULL,
  TRANSACTION_TYPE NUMERIC      NOT NULL,
  CONSTRAINT APP_USER_AUD_PK PRIMARY KEY (ID, VERSION_NUMBER)
);

DROP TABLE IF EXISTS USER_ROLE;
CREATE TABLE USER_ROLE
(
  ACTIVE_FLAG BOOLEAN DEFAULT TRUE NOT NULL,
  USER_ID     NUMERIC              NOT NULL,
  ROLE_ID     NUMERIC              NOT NULL,
  CONSTRAINT USER_ROLE_PK PRIMARY KEY (USER_ID, ROLE_ID, ACTIVE_FLAG)
);

DROP TABLE IF EXISTS USER_ROLE_AUD;
CREATE TABLE USER_ROLE_AUD
(
  ACTIVE_FLAG      BOOLEAN DEFAULT TRUE NOT NULL,
  USER_ID          NUMERIC              NOT NULL,
  ROLE_ID          NUMERIC              NOT NULL,
  VERSION_NUMBER   NUMERIC              NOT NULL,
  TRANSACTION_TYPE NUMERIC              NOT NULL,
  CONSTRAINT USER_ROLE_M_PK PRIMARY KEY (USER_ID, ROLE_ID, VERSION_NUMBER)
);

DROP TABLE IF EXISTS ROLE_PERMISSION;
CREATE TABLE ROLE_PERMISSION
(
  ACTIVE_FLAG BOOLEAN DEFAULT TRUE NOT NULL,
  ROLE_ID     NUMERIC              NOT NULL,
  PERMISSION  VARCHAR(200)         NOT NULL,
  CONSTRAINT ROLE_PERMISSION_PK PRIMARY KEY (ROLE_ID, PERMISSION, ACTIVE_FLAG)
);

DROP TABLE IF EXISTS ROLE_PERMISSION_AUD;
CREATE TABLE ROLE_PERMISSION_AUD
(
  ACTIVE_FLAG      BOOLEAN DEFAULT TRUE NOT NULL,
  ROLE_ID          NUMERIC              NOT NULL,
  PERMISSION       VARCHAR(200)         NOT NULL,
  VERSION_NUMBER   NUMERIC              NOT NULL,
  TRANSACTION_TYPE NUMERIC              NOT NULL,
  CONSTRAINT ROLE_PERMISSION_AUD_PK PRIMARY KEY (ROLE_ID, PERMISSION, VERSION_NUMBER)
);

-- APP Based Tables
-- DROP TABLE IF EXISTS ACTIVITY_LOCATION;
-- CREATE TABLE ACTIVITY_LOCATION
-- (
--   ID          NUMERIC      NOT NULL PRIMARY KEY,
--   NAME        VARCHAR(250) NOT NULL,
--   LOCATION    GEOMETRY(Point, 4326),
--   ACTIVE_FLAG BOOLEAN      NOT NULL
-- );
