package com.khel.runtime.security.type;

public enum Permission
{
  USER_REGISTER,
  USER_EDIT,
  UPDATE_USER_PASSWORD,

  //Participant permissions
  PARTICIPANT_HOME,
  PARTICIPANT_VIEW_EVENT,
  PARTICIPANT_SCHEDULE_EVENT,
  PARTICIPANT_CANCEL_SCHEDULE_EVENT,
  PARTICIPANT_UPDATE_PROFILE,
  PARTICIPANT_PAYMENT,
  PARTICIPANT_REQUEST_REFUND,
  //Organizer permissions
  ORGANIZER_HOME,
  ADD_GEO_LOCATION,
  EDIT_GEO_LOCATION,
  ADD_EVENT,
  EDIT_EVENT,
  DELETE_EVENT,
  ADD_SCHEDULE,
  VIEW_SCHEDULE,
  EDIT_SCHEDULE,
  DELETE_SCHEDULE,
  REQUEST_PAYMENT,
  //Trainer permissions
  //support
  SUPPORT_HOME,
  DELETE_GEO_LOCATION,
  //admin
  ADMIN_HOME,;
}
