package com.khel.runtime.security.type;

public enum Permission
{
  ADD_USER,
  DELETE_USER,
  EDIT_USER,
  ADD_PLAYER,
  DELETE_PLAYER,
  EDIT_PLAYER,
  ADD_FIELD,
  ADD_GAME,
  ADD_SCHEDULE,
  REGISTER_EVENT,
  ADMIN_HOME,
  PLAYER_HOME,
  ORGANIZER_HOME,
  SUPPORT_HOME,
  UPDATE_USER_PASSWORD,
  ADD_ADDRESS,
  //Participant permissions
  PARTICIPANT_VIEW_ACTIVITY,
  PARTICIPANT_SCHEDULE_ACTIVITY,
  PARTICIPANT_CANCEL_ACTIVITY,
  PARTICIPANT_UPDATE_PROFILE,
  PARTICIPANT_PAYMENT,;
}
